package provider

import (
	"context"
	"encoding/base64"
	"fmt"
	"strings"
	"time"

	"github.com/coderHArsitv2/higgsfield-clone/backend/internal/storage"
	"github.com/coderHArsitv2/higgsfield-clone/backend/pkg/httpx"
)

// OpenAI returns generated bytes rather than hosted URLs, so this adapter
// re-hosts through storage before handing anything back.
type OpenAI struct{ store storage.Storage }

func NewOpenAI(store storage.Storage) *OpenAI { return &OpenAI{store: store} }

func (o *OpenAI) ID() string      { return "openai" }
func (o *OpenAI) Name() string    { return "OpenAI" }
func (o *OpenAI) EnvKey() string  { return "OPENAI_API_KEY" }
func (o *OpenAI) DocsURL() string { return "https://platform.openai.com/api-keys" }

func (o *OpenAI) Models() []ModelSpec {
	return []ModelSpec{
		{ID: "openai/gpt-image-1", Name: "GPT Image 1", Modality: ModalityImage, CreditCost: 6, Featured: true,
			Description: "Best-in-class instruction following for edits and composited scenes.",
			Tags:        []string{"image", "editing"},
			Params: []ParamSpec{
				{Key: "size", Label: "Size", Kind: ParamSelect, Default: "1024x1024",
					Options: opts("1024x1024", "Square 1024", "1536x1024", "Landscape 1536×1024", "1024x1536", "Portrait 1024×1536")},
				{Key: "quality", Label: "Quality", Kind: ParamSelect, Default: "high",
					Options: opts("low", "Low", "medium", "Medium", "high", "High")},
				{Key: "n", Label: "Images", Kind: ParamNumber, Default: 1, Min: f64(1), Max: f64(4)},
			}, RefImages: 4},
		{ID: "openai/sora-2", Name: "Sora 2", Modality: ModalityVideo, CreditCost: 28, Featured: true,
			Description: "World simulation with accurate physics, object permanence and synced audio.",
			Tags:        []string{"video", "audio"},
			Params: []ParamSpec{
				{Key: "size", Label: "Size", Kind: ParamSelect, Default: "1280x720",
					Options: opts("1280x720", "Landscape 720p", "720x1280", "Portrait 720p", "1792x1024", "Wide 1792×1024")},
				{Key: "seconds", Label: "Duration", Kind: ParamSelect, Default: "8",
					Options: opts("4", "4 seconds", "8", "8 seconds", "12", "12 seconds")},
			}, RefImages: 1},
	}
}

func (o *OpenAI) client(key string) *httpx.Client {
	return httpx.New("https://api.openai.com", 180*time.Second).WithHeader("Authorization", "Bearer "+key)
}

func (o *OpenAI) Submit(ctx context.Context, req SubmitRequest) (SubmitResult, error) {
	switch req.Model.ID {
	case "openai/gpt-image-1":
		return o.submitImage(ctx, req)
	case "openai/sora-2":
		return o.submitVideo(ctx, req)
	}
	return SubmitResult{}, ErrUnsupportedModel
}

// Images come back on the same request, so this job is already finished when
// Submit returns and never reaches the polling worker.
func (o *OpenAI) submitImage(ctx context.Context, req SubmitRequest) (SubmitResult, error) {
	body := map[string]any{"model": "gpt-image-1", "prompt": req.Prompt}
	for k, v := range req.Params {
		body[k] = v
	}

	var res struct {
		Data []struct {
			B64 string `json:"b64_json"`
			URL string `json:"url"`
		} `json:"data"`
	}
	if err := o.client(req.APIKey).JSON(ctx, "POST", "/v1/images/generations", body, &res); err != nil {
		return SubmitResult{}, err
	}

	var assets []ResultAsset
	for i, d := range res.Data {
		switch {
		case d.URL != "":
			assets = append(assets, ResultAsset{Kind: "image", URL: d.URL})
		case d.B64 != "":
			raw, err := base64.StdEncoding.DecodeString(d.B64)
			if err != nil {
				return SubmitResult{}, fmt.Errorf("decode image %d: %w", i, err)
			}
			url, err := o.store.Put(ctx, fmt.Sprintf("gpt-image-%d.png", i), raw, "image/png")
			if err != nil {
				return SubmitResult{}, err
			}
			assets = append(assets, ResultAsset{Kind: "image", URL: url})
		}
	}
	if len(assets) == 0 {
		return SubmitResult{}, fmt.Errorf("openai returned no images")
	}
	return SubmitResult{Done: true, Assets: assets}, nil
}

func (o *OpenAI) submitVideo(ctx context.Context, req SubmitRequest) (SubmitResult, error) {
	body := map[string]any{"model": "sora-2", "prompt": req.Prompt}
	for k, v := range req.Params {
		body[k] = v
	}
	var res struct {
		ID     string `json:"id"`
		Status string `json:"status"`
	}
	if err := o.client(req.APIKey).JSON(ctx, "POST", "/v1/videos", body, &res); err != nil {
		return SubmitResult{}, err
	}
	if res.ID == "" {
		return SubmitResult{}, fmt.Errorf("openai did not return a video id")
	}
	return SubmitResult{ExternalID: res.ID}, nil
}

func (o *OpenAI) Poll(ctx context.Context, req PollRequest) (PollResult, error) {
	c := o.client(req.APIKey)
	var res struct {
		Status   string `json:"status"`
		Progress int    `json:"progress"`
		Error    *struct {
			Message string `json:"message"`
		} `json:"error"`
	}
	if err := c.JSON(ctx, "GET", "/v1/videos/"+req.ExternalID, nil, &res); err != nil {
		return PollResult{}, err
	}

	switch res.Status {
	case "queued", "in_progress", "processing":
		p := res.Progress
		if p <= 0 {
			p = 10
		}
		return PollResult{Progress: p}, nil
	case "failed":
		msg := "sora reported a failure"
		if res.Error != nil && res.Error.Message != "" {
			msg = res.Error.Message
		}
		return PollResult{Failed: true, Error: msg}, nil
	}

	raw, ctype, err := c.Bytes(ctx, "GET", "/v1/videos/"+req.ExternalID+"/content", nil)
	if err != nil {
		return PollResult{}, err
	}
	ext := "mp4"
	if strings.Contains(ctype, "webm") {
		ext = "webm"
	}
	url, err := o.store.Put(ctx, "sora-"+req.ExternalID+"."+ext, raw, ctype)
	if err != nil {
		return PollResult{}, err
	}
	return PollResult{Done: true, Progress: 100, Assets: []ResultAsset{{Kind: "video", URL: url}}}, nil
}
